name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # 替换为你的主分支名（如 master）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Show Flutter version
        run: flutter --version

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href /dark_web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
